server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-database
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect